geekshop/baskets/urls.py
from django.urls import path

from baskets.views import basket_add, basket_remove, basket_edit
# from baskets.views import BasketCreateView, BasketDeleteView, BasketUpdateView

app_name = 'baskets'
urlpatterns = [
    path('add/<int:product_id>/', basket_add, name='basket'),
    path('remove/<int:product_id>/', basket_remove, name='basket_remove'),
    path('edit/<int:id>/<int:quantity>/', basket_edit, name='basket_edit'),

]

# urlpatterns = [
#     path('add/<int:product_id>/', BasketCreateView.as_view(), name='basket'),
#     path('remove/<int:product_id>/', BasketDeleteView.as_view(), name='basket_remove'),
#     path('edit/<int:basket_id>/<int:quantity>/', BasketUpdateView.as_view(), name='basket_edit'),
#
# ]

geekshop/geekshop/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


from mainapp.views import IndexView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('products/', include('mainapp.urls', namespace='mainapp')),
    path('users/', include('users.urls', namespace='users')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('admins/', include('admins.urls', namespace='admins')),
    path("", include("social_django.urls", namespace="social")),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # import debug_toolbar
    #
    # urlpatterns += [path('^__debug_/', include(debug_toolbar.urls))]

geekshop/orders/urls.py
from django.urls import path

from orders.views import OrderList, OrderCreate, OrderUpdate, OrderDetail, OrderDelete, order_forming_complete, \
    OrderUpdateStatus, get_product_price

app_name = 'orders'

urlpatterns = [
    path('', OrderList.as_view(), name='list'),
    path('create/', OrderCreate.as_view(), name='create'),
    path('update/<int:pk>/', OrderUpdate.as_view(), name='update'),
    path('read/<int:pk>/', OrderDetail.as_view(), name='read'),
    path('delete/<int:pk>/', OrderDelete.as_view(), name='delete'),
    path('confirm/<int:pk>/', order_forming_complete, name='forming_complete'),
    path('update_status/<int:pk>/', OrderUpdateStatus.as_view(), name='update_status'),
    path('product/<int:pk>/price/', get_product_price, name='product_price'),

    ]

geekshop/users/urls.py
from django.urls import path

from .views import LoginListView, Logout, ProfileFormView, RegisterListView

app_name = 'users'
urlpatterns = [
    path('login/', LoginListView.as_view(), name='login'),
    path('register/', RegisterListView.as_view(), name='register'),
    path('profile/', ProfileFormView.as_view(), name='profile'),
    path('logout/', Logout.as_view(), name='logout'),
    path('verify/<str:email>/<str:activation_key>/', RegisterListView.verify, name='verify'),

]

geekshop/baskets/models.py
from django.db import models
from django.utils.functional import cached_property

from users.models import User
from mainapp.models import Product

# Create your models here.


# class BasketQuerySet(models.QuerySet):
#
#     def  delete(self, *args, **kwargs):
#         for item in self:
#             item.product.quantity += item.quantity
#             item.product.save()
#         super(BasketQuerySet, self).delete()


class Basket(models.Model):
    # objects = BasketQuerySet.as_manager()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='basket')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)
    update_timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Корзина для {self.user.username} | Продукт: {self.product.name}'

    def sum(self):
        return self.quantity * self.product.price

    def total_quantity(self):
        # baskets = Basket.objects.filter(user=self.user)
        baskets = self.get_items_cached
        return sum(basket.quantity for basket in baskets)

    def total_sum(self):
        # baskets = Basket.objects.filter(user=self.user)
        baskets = self.get_items_cached
        return sum(basket.sum() for basket in baskets)

    @cached_property
    def get_items_cached(self):
        return self.user.basket.select_related()

    # def delete(self, using=None, keep_parents=False):
    #     self.product.quantity += self.quantity
    #     self.product.save()
    #     super(Basket, self).delete()
    #
    # def save(self, force_insert=False, force_update=False, using=None,
    #          update_fields=None):
    #     if self.pk:
    #         self.product.quantity -= self.quantity - self.get_item(int(self.pk))
    #     else:
    #         self.product.quantity -= self.quantity
    #     self.product.save()
    #     super(Basket, self).save()

    @staticmethod
    def get_item(pk):
        return Basket.objects.get(pk=pk).quantity


    # Функции total_quantity, total_sum со статикметодом для работы templatetags/method.py:
    # @staticmethod
    # def total_quantity(user):
    #     baskets = Basket.objects.filter(user=user)
    #     return sum(basket.quantity for basket in baskets)
    #
    # @staticmethod
    # def total_sum(user):
    #     baskets = Basket.objects.filter(user=user)
    #     return sum(basket.sum() for basket in baskets)

geekshop/baskets/views.py
from django.db import connection
from django.db.models import F
from django.shortcuts import render, HttpResponseRedirect, redirect
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView

from geekshop.mixin import UserDispatchMixin, BaseClassContextMixin
from mainapp.models import Product
from baskets.models import Basket

# Create your views here.


@login_required
def basket_add(request, product_id):
    user_select = request.user
    product = Product.objects.get(id=product_id)
    baskets = Basket.objects.filter(user=user_select, product=product)
    if not baskets.exists():
        Basket.objects.create(user=user_select, product=product, quantity=1)
    else:
        basket = baskets.first()
        # basket.quantity += 1
        basket.quantity = F('quantity')+1
        basket.save()
        
        update_queries = list(filter(lambda x: 'UPDATE' in x['sql'], connection.quieries))
        print(f'basket_add {update_queries}')

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_remove(request, product_id):
    Basket.objects.get(id=product_id).delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required()
def basket_edit(request, id, quantity):
    if request.is_ajax():
        basket = Basket.objects.get(id=id)
        if quantity > 0:
            basket.quantity = quantity
            basket.save()
        else:
            basket.delete()

        baskets = Basket.objects.filter(user=request.user)
        context = {
            'baskets': baskets,
            # 'total_quantity': sum(basket.quantity for basket in baskets),
            # 'total_sum': sum(basket.sum() for basket in baskets),
        }
        result = render_to_string('baskets/baskets.html', context)
        return JsonResponse({'result': result})


# class BasketCreateView(CreateView, UserDispatchMixin, BaseClassContextMixin):
#     model = Basket
#     fields = ['product']
#     template_name = 'mainapp/products.html'
#     success_url = reverse_lazy('products:index')
#     title = 'Админка | Создание товара'
#
#     def post(self, request, *args, **kwargs):
#         if 'product_id' in kwargs:
#             product_id = kwargs['product_id']
#             if 'product_id':
#                 product = Product.objects.get(id=product_id)
#                 baskets = Basket.objects.filter(user=request.user, product=product)
#                 if not baskets.exists():
#                     Basket.objects.create(user=request.user, product=product, quantity=1)
#                 else:
#                     basket = baskets.first()
#                     basket.quantity += 1
#                     basket.save()
#         return redirect(self.success_url)
#
#
# class BasketDeleteView(DeleteView, UserDispatchMixin):
#     model = Basket
#     template_name = 'users/profile.html'
#     success_url = reverse_lazy('users:profile')
#
#
# class BasketUpdateView(UpdateView, UserDispatchMixin):
#     model = Basket
#     fields = ['product']
#     pk_url_kwarg = 'basket_id '
#     template_name = 'users/profile.html'
#     success_url = reverse_lazy('users:profile')
#
#     def get_context_data(self, **kwargs):
#         context = super(BasketUpdateView, self).get_context_data(**kwargs)
#         context['baskets'] = Basket.objects.filter(user=self.request.user),
#         return context
#
#     def get(self, request, *args, **kwargs):
#         super(BasketUpdateView, self).get(request, *args, **kwargs)
#         if request.is_ajax():
#             basket_id = kwargs[self.pk_url_kwarg]
#             quantity = kwargs['quantity']
#             baskets = Basket.objects.filter(id=basket_id)
#             if baskets.exists():
#                 basket = baskets.first()
#                 if quantity > 0:
#                     basket.quantity = quantity
#                     basket.save()
#                 else:
#                     basket.delete()
#
#             result = render_to_string('baskets/baskets.html', self.get_context_data(**kwargs), request=request)
#             return JsonResponse({'result': result})
#         return redirect(self.success_url)

geekshop/baskets/templates/baskets/baskets.html
{% load method %}

<div class="basket-list">

    {% if baskets %}
        <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
            {#            Корзина <span class="badge badge-secondary badge-pill">{{ total_quantity }}</span>#}
            Корзина <span class="badge badge-secondary badge-pill">{{ baskets.0.total_quantity }}</span>
            {#            Корзина <span class="badge badge-secondary badge-pill">{{ variable|total_quantity:user }}</span>#}
        </h4>
        {% for basket in baskets %}
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">{{ basket.product.name }}</h5>
                    <p class="card-text">{{ basket.product.description }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item bg-light">
                        <div class="row text-center">
                            <div class="col-lg-4">
                                {#                                <form action="{% url 'baskets:basket_edit' basket_id=basket.id quantity=basket.quantity %}">#}
                                {#                                    <input name="{{ basket.id }}" type="number" class="form-control"#}
                                {#                                           value="{{ basket.quantity }}" min="0">#}
                                <input name="{{ basket.id }}" type="number" class="form-control"
                                       value="{{ basket.quantity }}" min="1">
                                </form>
                            </div>
                            <div class="col-lg-4">{{ basket.sum }} руб.</div>
                            <div class="col-lg-4">
                                <a href="{% url 'baskets:basket_remove' basket.id %}">
                                    <i class="fas fa-trash"></i>
                                </a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        {% endfor %}
        <div class="card mb-3">
            <div class="card-footer">
                <p class="float-left">Итого</p>
                {#                <h4 class="float-right">{{ total_sum }} руб.</h4>#}
                <h4 class="float-right">{{ baskets.0.total_sum }} руб.</h4>
                {#                <h4 class="float-right">{{ variable|total_sum:user }} руб.</h4>#}
            </div>
        </div>
        <button type="button" class="btn btn-warning btn-round float-right">
            <a href="{% url 'orders:create' %}">
                Оформить
            </a>
        </button>
    {% else %}
        <h4 class="mt-3 mb-3 mb-3 text-center">Корзина пуста</h4>
    {% endif %}

</div>